server:
  servlet:
    context-path: /api
spring:
  application:
    name: server

oauth2:
  kakao:
    redirect-uri: http://localhost:5173/oauth2/redirected/kakao
    client-id: 453049e22bab83f704ea07c2f9142725
    secret-key: iangLE0GYUirQIkUaJOi7hae0g7rT1Ya
    scope:
      - profile_nickname
      - profile_image
    authorization-uri: https://kauth.kakao.com/oauth/authorize
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
    user-name-attribute: id
    grant-type: authorization_code